apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgtrds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mgtrds
  template:
    metadata:
      labels:
        app: mgtrds
    spec:
      containers:
      - image: okteto.dev/mgtrds:latest
        name: mgtrds
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5b7ef53c-2e25-439a-b715-b43859841b46"
        - name: Vless_Path
          value: "/vljhfg563"
        - name: Vmess_UUID
          value: "5b7ef53c-2e25-439a-b715-b43859841b46"
        - name: Vmess_Path
          value: "/vmkmnsre7592"
        - name: Share_Path
          value: "/v2link"
